export const DUCK_BITCOIN = 'bitcoin'

export const BITCOIN_WALLET_CREATE = 'BITCOIN/WALLET/CREATE'
export const BITCOIN_WALLET_CREATE_SUCCESS = 'BITCOIN/WALLET/CREATE_SUCCESS'
export const BITCOIN_WALLET_CREATE_FAILURE = 'BITCOIN/WALLET/CREATE_FAILURE'
