export const DUCK_WEB3 = 'web3'

export const WEB3_LISTENER_CONNECT = 'WEB3_LISTENER_CONNECT'
export const WEB3_LISTENER_CONNECT_FAILURE = 'WEB3_LISTENER_CONNECT_FAILURE'
export const WEB3_LISTENER_CONNECT_SUCCESS = 'WEB3_LISTENER_CONNECT_SUCCESS'


export const WEB3_LISTENER_RECONNECT = 'WEB3_LISTENER_RECONNECT'
export const WEB3_LISTENER_RECONNECT_FAILURE = 'WEB3_LISTENER_RECONNECT_FAILURE'
export const WEB3_LISTENER_RECONNECT_SUCCESS = 'WEB3_LISTENER_RECONNECT_SUCCESS'

export const WEB3_LISTENER_SUBSCRIBE = 'WEB3_LISTENER_SUBSCRIBE'
export const WEB3_LISTENER_SUBSCRIBE_FAILURE = 'WEB3_LISTENER_SUBSCRIBE_FAILURE'
export const WEB3_LISTENER_SUBSCRIBE_SUCCESS = 'WEB3_LISTENER_SUBSCRIBE_SUCCESS'

export const WEB3_LISTENER_APPEND_CONTRACT = 'WEB3_LISTENER_APPEND_CONTRACT'
export const WEB3_LISTENER_DISCONNECT = 'WEB3_LISTENER_DISCONNECT'
export const WEB3_LISTENER_INCOMPATIBLE_NETWORK = 'WEB3_LISTENER_INCOMPATIBLE_NETWORK'
export const WEB3_LISTENER_RESET = 'WEB3_LISTENER_RESET'
export const WEB3_LISTENER_UNSUBSCRIBE = 'WEB3_LISTENER_UNSUBSCRIBE'
