export const DUCK_WEB3 = 'web3'

export const MIDDLEWARE_CONNECT = 'MIDDLEWARE/CONNECT'
export const MIDDLEWARE_CONNECT_FAILURE = 'MIDDLEWARE/CONNECT_FAILURE'
export const MIDDLEWARE_CONNECT_SUCCESS = 'MIDDLEWARE/CONNECT_SUCCESS'
export const MIDDLEWARE_DISCONNECT = 'MIDDLEWARE/DISCONNECT'
export const MIDDLEWARE_SUBSCRIBE = 'MIDDLEWARE/SUBSCRIBE'
export const MIDDLEWARE_SUBSCRIBE_FAILURE = 'MIDDLEWARE/SUBSCRIBE_FAILURE'
export const MIDDLEWARE_SUBSCRIBE_SUCCESS = 'MIDDLEWARE/SUBSCRIBE_SUCCESS'
export const MIDDLEWARE_UNSUBSCRIBE = 'MIDDLEWARE/UNSUBSCRIBE'

export const WEB3_LISTENER_APPEND_CONTRACT = 'WEB3/LISTENER/APPEND_CONTRACT'
export const WEB3_LISTENER_RESET = 'WEB3/LISTENER/RESET'
