/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const TREZOR_INIT = 'TREZOR/INIT'
export const TREZOR_INIT_SUCCESS = 'TREZOR/INIT_SUCCESS'
export const TREZOR_INIT_FAILURE = 'TREZOR/INIT_FAILURE'

export const TREZOR_CONNECTED = 'TREZOR/STATUS/CONNECTED'
export const TREZOR_DISCONNECTED = 'TREZOR/STATUS/DISCONNECTED'

export const TREZOR_GET_ADDRESS = 'TREZOR/METHOD/GET_ADDRESS'
export const TREZOR_GET_ADDRESS_SUCCESS = 'TREZOR/METHOD/GET_ADDRESS_SUCCESS'
export const TREZOR_GET_ADDRESS_FAILURE = 'TREZOR/METHOD/GET_ADDRESS_FAILURE'

export const TREZOR_GET_PUBLIC_KEY = 'TREZOR/METHOD/GET_PIBLIC_KEY'
export const TREZOR_GET_PUBLIC_KEY_SUCCESS = 'TREZOR/METHOD/GET_PIBLIC_KEY_SUCCESS'
export const TREZOR_GET_PUBLIC_KEY_FAILURE = 'TREZOR/METHOD/GET_PIBLIC_KEY_FAILURE'

export const TREZOR_ETHEREUM_GET_ADDRESS = 'TREZOR/METHOD/ETHEREUM_GET_ADDRESS'
export const TREZOR_ETHEREUM_GET_ADDRESS_SUCCESS = 'TREZOR/METHOD/ETHEREUM_GET_ADDRESS_SUCCESS'
export const TREZOR_ETHEREUM_GET_ADDRESS_FAILURE = 'TREZOR/METHOD/ETHEREUM_GET_ADDRESS_FAILURE'

export const TREZOR_SIGN_TRANSACTION = 'TREZOR/METHOD/SIGN_TRANSACTION'
export const TREZOR_SIGN_TRANSACTION_SUCCESS = 'TREZOR/METHOD/SIGN_TRANSACTION_SUCCESS'
export const TREZOR_SIGN_TRANSACTION_FAILURE = 'TREZOR/METHOD/SIGN_TRANSACTION_FAILURE'
