/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const BITCOIN_GET_ADDRESS = 'BITCOIN_GET_ADDRESS'
export const BITCOIN_GET_ADDRESS_SUCCESS = 'BITCOIN_GET_ADDRESS_SUCCESS'
export const BITCOIN_GET_ADDRESS_FAILURE = 'BITCOIN_GET_ADDRESS_FAILURE'

export const BITCOIN_SIGN_TRANSACTION = 'BITCOIN_SIGN_TRANSACTION'
export const BITCOIN_SIGN_TRANSACTION_SUCCESS = 'BITCOIN_SIGN_TRANSACTION_SUCCESS'
export const BITCOIN_SIGN_TRANSACTION_FAILURE = 'BITCOIN_SIGN_TRANSACTION_FAILURE'
