/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */
export const RABBITMQ_CONNECT = 'RABBITMQ/CONNECT'
export const RABBITMQ_CONNECT_SUCCESS = 'RABBITMQ/CONNECT_SUCCESS'
export const RABBITMQ_CONNECT_FAILURE = 'RABBITMQ/CONNECT_FAILURE'

export const RABBITMQ_DISCONNECT = 'RABBITMQ/DISCONNECT'
export const RABBITMQ_DISCONNECT_SUCCESS = 'RABBITMQ/DISCONNECT_SUCCESS'
export const RABBITMQ_DISCONNECT_FAILURE = 'RABBITMQ/DISCONNECT_FAILURE'

export const RABBITMQ_RECONNECT = 'RABBITMQ/RECONNECT'
export const RABBITMQ_RECONNECT_SUCCESS = 'RABBITMQ/RECONNECT_SUCCESS'
export const RABBITMQ_RECONNECT_FAILURE = 'RABBITMQ/RECONNECT_FAILURE'

export const RABBITMQ_SUBSCRIBE = 'RABBITMQ/SUBSCRIBE'
export const RABBITMQ_SUBSCRIBE_SUCCESS = 'RABBITMQ/SUBSCRIBE_SUCCESS'
export const RABBITMQ_SUBSCRIBE_FAILURE = 'RABBITMQ/SUBSCRIBE_FAILURE'

export const RABBITMQ_UNSUBSCRIBE = 'RABBITMQ/UNSUBSCRIBE'
export const RABBITMQ_UNSUBSCRIBE_SUCCESS = 'RABBITMQ/UNSUBSCRIBE_SUCCESS'
export const RABBITMQ_UNSUBSCRIBE_FAILURE = 'RABBITMQ/UNSUBSCRIBE_FAILURE'

export const RABBITMQ_UNSUBSCRIBE_BLOCKCHAIN = 'RABBITMQ/UNSUBSCRIBE_BLOCKCHAIN'
export const RABBITMQ_UNSUBSCRIBE_BLOCKCHAIN_SUCCESS = 'RABBITMQ/UNSUBSCRIBE_BLOCKCHAIN_SUCCESS'
export const RABBITMQ_UNSUBSCRIBE_BLOCKCHAIN_FAILURE = 'RABBITMQ/UNSUBSCRIBE_BLOCKCHAIN_FAILURE'
