/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const URL = 'https://streamer.cryptocompare.com/'

export const CRYPTOCOMPARE_CONNECT = 'MIDDLEWARE/CRYPTOCOMPARE/CONNECT'
export const CRYPTOCOMPARE_CONNECT_FAILURE = 'MIDDLEWARE/CRYPTOCOMPARE/CONNECT_FAILURE'
export const CRYPTOCOMPARE_CONNECT_SUCCESS = 'MIDDLEWARE/CRYPTOCOMPARE/CONNECT_SUCCESS'
export const CRYPTOCOMPARE_DISCONNECT = 'MIDDLEWARE/CRYPTOCOMPARE/DISCONNECT'
export const CRYPTOCOMPARE_DISCONNECT_FAILURE = 'MIDDLEWARE/CRYPTOCOMPARE/DISCONNECT_FAILURE'
export const CRYPTOCOMPARE_DISCONNECT_SUCCESS = 'MIDDLEWARE/CRYPTOCOMPARE/DISCONNECT_SUCCESS'
export const CRYPTOCOMPARE_SET_EVENT_HANDLER = 'MIDDLEWARE/CRYPTOCOMPARE/SET_EVENT_HANDLER'
export const CRYPTOCOMPARE_SET_EVENT_HANDLER_FAILURE = 'MIDDLEWARE/CRYPTOCOMPARE/SET_EVENT_HANDLER_FAILURE'
export const CRYPTOCOMPARE_SET_EVENT_HANDLER_SUCCESS = 'MIDDLEWARE/CRYPTOCOMPARE/SET_EVENT_HANDLER_SUCCESS'
export const CRYPTOCOMPARE_START_PRICES_POLLING = 'MIDDLEWARE/CRYPTOCOMPARE/START_PRICES_POLLING'
export const CRYPTOCOMPARE_STOP_PRICES_POLLING = 'MIDDLEWARE/CRYPTOCOMPARE/STOP_PRICES_POLLING'
export const CRYPTOCOMPARE_SUBSCRIBE = 'MIDDLEWARE/CRYPTOCOMPARE/SUBSCRIBE'
export const CRYPTOCOMPARE_SUBSCRIBE_FAILURE = 'MIDDLEWARE/CRYPTOCOMPARE/SUBSCRIBE_FAILURE'
export const CRYPTOCOMPARE_SUBSCRIBE_SUCCESS = 'MIDDLEWARE/CRYPTOCOMPARE/SUBSCRIBE_SUCCESS'
export const CRYPTOCOMPARE_UNSET_EVENT_HANDLER = 'MIDDLEWARE/CRYPTOCOMPARE/UNSET_EVENT_HANDLER'
export const CRYPTOCOMPARE_UNSET_EVENT_HANDLER_FAILURE = 'MIDDLEWARE/CRYPTOCOMPARE/UNSET_EVENT_HANDLER_FAILURE'
export const CRYPTOCOMPARE_UNSET_EVENT_HANDLER_SUCCESS = 'MIDDLEWARE/CRYPTOCOMPARE/UNSET_EVENT_HANDLER_SUCCESS'
export const CRYPTOCOMPARE_UNSUBSCRIBE = 'MIDDLEWARE/CRYPTOCOMPARE/UNSUBSCRIBE'
export const CRYPTOCOMPARE_UNSUBSCRIBE_FAILURE = 'MIDDLEWARE/CRYPTOCOMPARE/UNSUBSCRIBE_FAILURE'
export const CRYPTOCOMPARE_UNSUBSCRIBE_SUCCESS = 'MIDDLEWARE/CRYPTOCOMPARE/UNSUBSCRIBE_SUCCESS'
export const CRYPTOCOMPARE_UPDATE_MARKET_LAST = 'MIDDLEWARE/CRYPTOCOMPARE/UPDATE_MARKET_LAST'
export const CRYPTOCOMPARE_UPDATE_MARKET_PRICES = 'MIDDLEWARE/CRYPTOCOMPARE/UPDATE_MARKET_PRICES'
export const CRYPTOCOMPARE_UPDATE_MARKET_RATES = 'MIDDLEWARE/CRYPTOCOMPARE/UPDATE_MARKET_RATES'
