/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_NODES = 'nodes'

export const NODES_INIT = 'NODES/INIT'
export const NODES_NETWORK_SWITCH = 'NODES/NETWORK/SWITCH'
export const NODES_NETWORK_SELECT = 'NODES/NETWORK/SELECT'

export const WEB3_LISTENER_ADD_CUSTOM_NODE = 'WEB3/LISTENER/ADD_CUSTOM_NODE'
export const WEB3_LISTENER_CONNECTED = 'WEB3/LISTENER/CONNECTED'
export const WEB3_LISTENER_DISABLE = 'WEB3/LISTENER/DISABLE'
export const WEB3_LISTENER_DISCONNECTED = 'WEB3/LISTENER/DISCONNECTED'
export const WEB3_LISTENER_ENABLE = 'WEB3/LISTENER/ENABLE'
export const WEB3_LISTENER_ERROR = 'WEB3/LISTENER/ERROR'
export const WEB3_LISTENER_GET_WEB3 = 'WEB3/LISTENER/GET_WEB3'
export const WEB3_LISTENER_GET_WEB3_PROVIDER = 'WEB3/LISTENER/WEB3_PROVIDER'
export const WEB3_LISTENER_RESUBSCRIBE_CONTRACTS = 'WEB3/LISTENER/RESUBSCRIBE_CONTRACTS'
export const WEB3_LISTENER_SWITCH = 'WEB3/LISTENER/SWITCH'
export const WEB3_LISTENER_SYNC_STATUS = 'WEB3/LISTENER/SYNC_STATUS'
export const WEB3_LISTENER_SYNC_STATUS_STOP = 'WEB3/LISTENER/SYNC_STATUS_STOP'
export const WEB3_LISTENER_SET_EXTERNAL_PROVIDER = 'WEB3/LISTENER/SET_EXTERNAL_PROVIDER'
export const WEB3_LISTENER_INCOMPATIBLE_NETWORK = 'WEB3/LISTENER/INCOMPATIBLE_NETWORK'

export const ETHEREUM_TOKEN_TRANSFER = 'ETHEREUM/TOKEN/TRANSFER'
