/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_ETHEREUM = 'ethereum'

export const ETHEREUM_TOKENS_APPEND_LIST = 'ETHEREUM/TOKENS/APPEND_LIST'

export const ETHEREUM_WALLET_CREATE = 'ETHEREUM/WALLET/CREATE'
export const ETHEREUM_WALLET_CREATE_SUCCESS = 'ETHEREUM/WALLET/CREATE_SUCCESS'
export const ETHEREUM_WALLET_CREATE_FAILURE = 'ETHEREUM/WALLET/CREATE_FAILURE'

export const ETHEREUM_DECRYPT_WALLET_GET_PK_SUCCESS = 'ETHEREUM/WALLET/DECRYPT/GET_PRIVATE_KEY_SUCCESS'
export const ETHEREUM_DECRYPT_WALLET_GET_PK_FAILURE = 'ETHEREUM/WALLET/DECRYPT/GET_PRIVATE_KEY_FAILURE'
